### ISSUE TITLE
Docker mysql connection

### ISSUE THREAD

**Issue by facundocasagrande** [odan/slim4-skeleton#73]
Hello
This I don't think is a bug but I need help

I try to connect to a mysql server on another machine on the network, I change all the configuration files that I have found, but it always takes the address of the docker host.

Any help is appreciated

<img width="1347" alt="Captura de Pantalla 2021-07-05 a la(s) 13 32 03" src="https://user-images.githubusercontent.com/20067712/124500164-a69b6700-dd95-11eb-88e5-9ef1451b74c6.png">
<img width="376" alt="Captura de Pantalla 2021-07-05 a la(s) 13 31 48" src="https://user-images.githubusercontent.com/20067712/124500170-a8652a80-dd95-11eb-8416-85aaa96819e1.png">

**Comment by odan** [comment]
It looks like the network connection to the mysql server works so far. But then mysql blocks the incoming connection because the remote host (the docker instance) is not granted. So make sure that the user `externo` exits and has permission for the host `192.168.4.104`. See [here](https://stackoverflow.com/questions/10236000/allow-all-remote-connections-mysql)

**Comment by facundocasagrande** [comment]
What a shame, it was a password error I must sleep better. Sorry
